project:
  type: book

book:
  title: "Advanced descriptive analysis of tabular data"
  author: "Antoine Soetewey & CÃ©dric Heuchenne"
  date: today
  chapters:
    - index.qmd
    - about.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  search: true
  repo-url: https://github.com/AntoineSoetewey/Advanced-descriptive-analysis-of-tabular-data
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  cover-image: cover.png

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub: default

editor: visual

